sudo: required

language: php

php:
  - 5.6

services:
  - docker

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

after_success:
  - if [ "$TRAVIS_BRANCH" == "testing" ]; then
    docker build -t "$DOCKER_HUB_ORG"/traspaso:v"$TRAVIS_BUILD_NUMBER" .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$DOCKER_HUB_ORG"/traspaso:v"$TRAVIS_BUILD_NUMBER";
    fi
